# Generated by Django 5.1.2 on 2024-10-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.TextField(default='desc'),
        ),
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
