# Generated by Django 5.1.2 on 2024-10-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_producto_description_producto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.TextField(default='img'),
        ),
    ]
