# Generated by Django 5.1.2 on 2024-10-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.TextField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.IntegerField(max_length=6),
        ),
    ]
