# Generated by Django 5.1.2 on 2024-10-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_producto_description_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.TextField(default='none', max_length=200),
        ),
    ]
