# Generated by Django 5.1.2 on 2024-10-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.IntegerField(),
        ),
    ]
