# Generated by Django 5.1.2 on 2024-10-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_producto_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
