# Generated by Django 5.1.2 on 2024-10-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.TextField(default='<django.db.models.fields.CharField>.png'),
        ),
    ]
